# Generated by Django 5.0.2 on 2024-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('lang', models.CharField(max_length=10)),
                ('audio_path', models.FileField(upload_to='media/')),
                ('datetime', models.DateTimeField()),
                ('loc', models.CharField(max_length=10)),
            ],
        ),
    ]
